import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/providers/StoreProvider";
import ToastContext from "@/providers/ToastProvider";

const inter = Inter({
  subsets : ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        cz-shortcut-listen="true"
        className={`h-full ${inter.className} antialiased`}
      >
        <StoreProvider>
          <ToastContext />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
